name: solo_wallet
description: "Solo wallet for crypto currency"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.2.3
  bloc: ^8.1.4
  dio: ^5.4.3+1
  iconsax: ^0.0.8
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  starknet: ^0.1.0


flutter:
  generate: true

  assets: 
    - assets/fonts/
    - assets/icons/

  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf    
        - asset: assets/fonts/Inter/Inter-Regular.ttf    
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf    
        - asset: assets/fonts/Inter/Inter-Thin.ttf    


  uses-material-design: true

  